services:

  nginx:
    image: nginx:alpine
    container_name: nginx

    ports:
      - "80:80"
      - "443:443"

    depends_on:
      apache:
        condition: service_healthy
      rsyslog:
        condition: service_started

    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --no-check-certificate --tries=1 --spider https://127.0.0.1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro

    networks:
      - frontend

  rsyslog:
    build: ./rsyslog
    container_name: rsyslog

    environment:
      REMOTE_SYSLOG_IP: ${REMOTE_SYSLOG_IP}

    volumes:
      - rsyslog_queue:/var/spool/rsyslog
      - rsyslog_logs:/var/log

    depends_on:
      syslog-receiver:
        condition: service_started

    networks:
      - frontend


  syslog-receiver:
    build: ./syslog-receiver
    container_name: syslog-receiver

    expose:
      - "514"

    networks:
      - frontend

  apache:
    build: ./apache
    container_name: apache

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    depends_on:
      postgres:
        condition: service_healthy

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

    expose:
      - "80"
    networks:
      - backend
      - frontend

  postgres:
    image: postgres:16
    container_name: postgres
    
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro

    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf
      - -c
      - hba_file=/etc/postgresql/pg_hba.conf

    networks:
      - backend

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16

  frontend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/16

volumes:
  postgres_data:
  rsyslog_queue:
  rsyslog_logs:
