global(
    workDirectory="/var/spool/rsyslog"
)

module(load="imudp")

input(
    type="imudp"
    port="514"
)

# Сохраняем локальную копию nginx access_log
local6.* /var/log/nginx.log

# Отправляем nginx access_log на удаленный syslog
local6.* action(
    type="omfwd"
    target="${REMOTE_SYSLOG_IP}"
    port="514"
    protocol="tcp"

    action.resumeRetryCount="-1"

    # Постоянная дисковая очередь
    queue.type="Disk"
    queue.filename="nginx_remote"
    queue.spoolDirectory="/var/spool/rsyslog"

    queue.maxdiskspace="1g"
    queue.maxfilesize="10m"

    queue.saveOnShutdown="on"
)
