global(
    workDirectory="/var/spool/rsyslog"
)

module(load="imudp")

input(
    type="imudp"
    port="514"
)

local6.* /var/log/nginx.log

local6.* action(
    type="omfwd"
    target="${REMOTE_SYSLOG_IP}"
    port="514"
    protocol="tcp"

    action.resumeRetryCount="-1"

    queue.filename="nginx_remote"
    queue.spoolDirectory="/var/spool/rsyslog"

    queue.maxdiskspace="1g"
    queue.maxfilesize="10m"

    queue.saveOnShutdown="on"
)
